name: "Build PS4 Payload"

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 1

      - name: Build payload
        run: |
          sudo apt update && sudo apt install yasm
          ls -l
          bash -c "cd linux && make"

      - name: Upload payload.bin
        uses: actions/upload-artifact@v4
        with:
          name: payload
          path: linux/payload.bin
